import {
  getFrameLabel,
  getProduct360Frames,
} from "@/lib/product360Frames";

export const VIEW_360_ORDER = ["front", "side", "top", "bottom"] as const;

export type View360Id = (typeof VIEW_360_ORDER)[number] | `f${number}`;

export interface View360 {
  id: string;
  label: string;
  src: string;
}

export function getImageBasename(src: string): string {
  const filename = src.split("/").pop() ?? "";
  return filename.replace(/\.[^.]+$/i, "").toLowerCase();
}

/** True for r01–r36 spin frames stored under `360/` or matching spin naming. */
export function isSpinFrameImage(src: string): boolean {
  if (/\/360\//i.test(src)) return true;
  return /^r\d{2}$/.test(getImageBasename(src));
}

/** Auto-generated lifestyle placeholder graphics (not real product photos). */
export function isLifestylePlaceholderImage(src: string): boolean {
  const base = getImageBasename(src);
  return base === "lifestyle" || base.startsWith("lifestyle-");
}

/** Auto-generated jff-* SVG placeholders (not real product photography). */
const PLACEHOLDER_SVG_BASENAMES = new Set([
  "main",
  "front",
  "side",
  "top",
  "bottom",
]);

export function isAutoGeneratedPlaceholderImage(src: string): boolean {
  if (!/\.svg$/i.test(src)) return false;
  if (!/\/products\/jff-\d+\//i.test(src)) return false;
  return PLACEHOLDER_SVG_BASENAMES.has(getImageBasename(src));
}

/** Images excluded from product galleries and generated catalog data. */
export function isExcludedProductImage(src: string): boolean {
  return (
    isSpinFrameImage(src) ||
    isLifestylePlaceholderImage(src) ||
    isAutoGeneratedPlaceholderImage(src)
  );
}

/**
 * Product gallery images — real photos only (no spin frames or placeholders).
 */
export function getGalleryImages(images: string[]): string[] {
  return images.filter((src) => !isExcludedProductImage(src));
}

/**
 * Extract rotation frames for legacy consumers (View360 shape).
 * Returns null if fewer than 2 frames are available.
 */
export function get360Views(images: string[]): View360[] | null {
  const { rotationFrames } = getProduct360Frames(images);
  if (rotationFrames.length < 2) return null;

  return rotationFrames.map((src, index) => ({
    id: getImageBasename(src),
    label: getFrameLabel(src, index),
    src,
  }));
}

/** Images that are not part of the 360 rotation set (main, lifestyle, etc.). */
export function getSupplementaryImages(
  images: string[],
  views360: View360[] | null
): string[] {
  if (!views360) return images;
  return getProduct360Frames(images).supplementaryImages;
}

export function find360ViewIndex(views: View360[], src: string): number {
  return views.findIndex((v) => v.src === src);
}

export { getProduct360Frames, has360Rotation } from "@/lib/product360Frames";
export { getViewerFrames, getFrameLabel } from "@/lib/viewerFrames";
